name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: dennisameling/ftp-upload-action@v1
      with:
        server: files.000webhost.com
        username: projetnf083
        password: iCwpRiCu7(Pxzz((Ent*
        server_dir: public_html/
