name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload bundle
      uses: bayssmekanique/action-simple-file-upload@v1
      with:
       user: projetnf083
       password: iCwpRiCu7(Pxzz((Ent*
       host: files.000webhost.com
       dest: public_html/
