name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload bundle
      uses: sebastianpopp/ftp-action@releases/v2
      with:
       user: projetnf083
       password: iCwpRiCu7(Pxzz((Ent*
       host: files.000webhost.com
       remoteDir: "public_html/"
