name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload bundle
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
       ftp_host: ${{ secrets.FTP_HOST }}
       ftp_username: projetnf083
       ftp_password: iCwpRiCu7(Pxzz((Ent*
       dist_target_dir: "public_html/"
       delete: "true"
       exclude: "'^logs/' '^README.md'"
