name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: genietim/ftp-action@releases/v4
      with:
        host: files.000webhost.com
        user: projetnf083
        password: iCwpRiCu7(Pxzz((Ent*
        remoteDir: "public_html/"
