name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload bundle
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
       username: projetnf083
       password: iCwpRiCu7(Pxzz((Ent*
       server: files.000webhost.com
       server-dir: public_html/
